export { Header } from './Header'
export { Footer } from './Footer'
export { HeroSection } from './HeroSection'
export { AboutSection } from './AboutSection'
export { ExperienceSection } from './ExperienceSection'
export { SkillsSection } from './SkillsSection'
export { FamousQuotesSection } from './FamousQuotesSection'
export { ProjectsSection } from './ProjectsSection'
export { ContactSection } from './ContactSection'
// export { TestimonialsSection } from './TestimonialsSection'